### ISSUE TITLE
PHP Acronym

### ISSUE THREAD

**Issue by jplath** [BloombergMedia/whatiscode#83] opened 2015-06-15 22:03 UTC
Isn't PHP short for PHP: Hypertext Preprocessor and not "Personal Home Page/Forms Interpreter" ?

http://php.net/manual/en/faq.general.php#faq.general.acronym

Although we've moved to Python at the dev shop I run, PHP is one of my favorite examples of a recursive acronym.

**Comment by 1wheel** [comment] 2015-06-16 01:34
Duplicate of #6

**Closed by 1wheel** 2015-06-16 01:34 UTC
