### ISSUE TITLE
Can you add anchors to sections?

### ISSUE THREAD

**Issue by RioBrewster** [BloombergMedia/whatiscode#89] opened 2015-06-16 18:50 UTC
I'd really like to share pieces of this with others, but there's no way to do:

http://www.bloomberg.com/graphics/2015-paul-ford-what-is-code/index.html#section6-5

Or if there is I haven't figured it out.

**Comment by tophtucker** [comment] 2015-06-19 19:31
you're absolutely right. duplicate of #46

**Closed by tophtucker** 2015-06-19 19:31 UTC
Labels: duplicate
